    python experiments/span_train.py \
    -data_path data/ontonotes/const/nonterminal \
    -config_path data/transformer${1}_30/config.json \
    -pretrain_dir data/transformer${1}_30 \
    -task ctl -model_type transformer \
    -batch_size 64 \
    -eval_batch_size 4 \
    -criteria bce \
    -pool_methods max \
    -fine_tune \
    -slurm_comment maxt${1}_nt
