    torchrun --standalone --nnodes=1 --nproc_per_node=1 experiments/r2d2+_glue_trainer.py \
    --max_grad_norm 1.0 --lr 5e-5 --parser_lr 1e-2 \
    --config_path data/en_config/fast_r2d2_hyper_attn_tiny.json \
    --vocab_dir data/en_config \
    --task_type mnli --glue_dir data/glue/MNLI \
    --cache_dir data_cio_cache_dir \
    --max_batch_len 512 --max_batch_size 4 \
    --output_dir data/debug_save \
    --epochs 10  \
    --model_name fastr2d2+_iter \
    --enable_epoch_eval