    python experiments/span_train.py \
    -data_path data/ontonotes/coref \
    -config_path data/r2d2+_share_30/config.json \
    -pretrain_dir data/r2d2+_share_30 \
    -task coref -model_type r2d2 \
    -share \
    -mlm_rate 0.15 -decline_rate 0.015 \
    -fine_tune \
    -use_argmax \
    -criteria ce \
    -slurm_comment share
